import { LAYOUT_TEMPLATES } from "~/config/layoutTemplates";
import type { SectionType, SectionRegistryEntry } from "~/types/editor";

export const DEFAULT_SECTION_SEQUENCE: Exclude<SectionType, "custom">[] = [
  "navbar",
  "hero",
  "features",
  "cta",
  "testimonials",
  "faq",
  "footer",
];

const ALL_LAYOUT_IDS = LAYOUT_TEMPLATES.map((layout) => layout.id);
const ALL_BLOCK_TYPES: SectionRegistryEntry["allowedBlockTypes"] = [
  "heading",
  "text",
  "button",
  "card",
  "image",
  "icon",
  "spacer",
  "badge",
  "divider",
  "list",
  "quote",
  "date",
  "rsvp",
];

export const SECTION_REGISTRY: Record<SectionType, SectionRegistryEntry> = {
  navbar: {
    label: "Navigation",
    icon: "menu",
    description: "Top navigation bar with logo and links",
    allowedLayouts: [
      "1col",
      "1col-left",
      "2col-1-5",
      "2col-2-4",
      "2col-3-3",
      "2col-4-2",
      "2col-5-1",
      "3col-1-1-4",
      "3col-1-2-3",
      "3col-1-4-1",
      "3col-2-2-2",
      "3col-3-2-1",
      "3col-4-1-1",
    ],
    defaultLayoutId: "3col-1-4-1",
    defaultBlocks: [
      {
        type: "heading",
        slot: "col-1",
        order: 0,
        props: { text: "Astra Studio" },
        style: {
          fontSize: "xl",
          fontWeight: "semibold",
          textAlign: "left",
        },
      },
      {
        type: "list",
        slot: "col-2",
        order: 0,
        props: {
          items: [
            { text: "Home", url: "#" },
            { text: "Features", url: "#" },
            { text: "Pricing", url: "#" },
            { text: "About", url: "#" },
            { text: "Blog", url: "#" },
            { text: "Contact", url: "#" },
          ],
          ordered: false,
          inline: true,
        },
        style: { fontSize: "sm", textAlign: "center" },
      },
      {
        type: "button",
        slot: "col-3",
        order: 0,
        props: { text: "Start Free", url: "#" },
        style: { fontSize: "sm", textAlign: "right" },
      },
    ],
    defaultStyle: {
      backgroundColor: "#0a120f",
      paddingY: 20,
      backgroundType: "solid",
    },
    allowedBlockTypes: ["heading", "text", "button", "icon", "list", "image", "badge", "divider", "date", "spacer"],
    maxBlocksPerSlot: 6,
  },

  hero: {
    label: "Hero Section",
    icon: "star",
    description: "Main hero area with headline, subheadline, and CTA",
    allowedLayouts: ["1col", "1col-left", "2col-3-3", "2col-4-2", "2col-2-4", "2col-3-3-rev"],
    defaultLayoutId: "2col-3-3",
    defaultBlocks: [
      {
        type: "badge",
        slot: "col-1",
        order: 0,
        props: { text: "Now Available" },
        style: { fontSize: "base", marginBottom: 12 },
      },
      {
        type: "heading",
        slot: "col-1",
        order: 1,
        props: { text: "Build Faster. Design Better." },
        style: { fontSize: "5xl", fontWeight: "bold", marginBottom: 16 },
      },
      {
        type: "text",
        slot: "col-1",
        order: 2,
        props: { text: "Create stunning, high-converting landing pages in minutes without writing a single line of code." },
        style: { fontSize: "lg", marginBottom: 24, opacity: 70 },
      },
      {
        type: "button",
        slot: "col-1",
        order: 3,
        props: { text: "Start Building Free", url: "#" },
        style: { fontSize: "lg" },
      },
      {
        type: "image",
        slot: "col-2",
        order: 0,
        props: { src: "", alt: "Hero image" },
        style: { width: "full" },
      },
    ],
    defaultStyle: {
      backgroundColor: "#101b17",
      paddingY: 80,
      backgroundType: "solid",
    },
    allowedBlockTypes: ["heading", "text", "button", "card", "image", "icon", "spacer", "badge", "divider", "date", "rsvp"],
  },

  features: {
    label: "Features Grid",
    icon: "grid_view",
    description: "Showcase features or benefits with icons",
    allowedLayouts: ["1col", "2col-3-3", "3col-2-2-2"],
    defaultLayoutId: "3col-2-2-2",
    defaultBlocks: [
      {
        type: "icon",
        slot: "col-1",
        order: 0,
        props: { icon: "bolt" },
        style: { fontSize: "xl", marginBottom: 8 },
      },
      {
        type: "heading",
        slot: "col-1",
        order: 1,
        props: { text: "Lightning Fast" },
        style: { fontSize: "xl", fontWeight: "semibold", marginBottom: 8 },
      },
      {
        type: "text",
        slot: "col-1",
        order: 2,
        props: { text: "Optimized for speed and performance out of the box." },
        style: { fontSize: "sm", opacity: 70 },
      },
      {
        type: "icon",
        slot: "col-2",
        order: 0,
        props: { icon: "palette" },
        style: { fontSize: "xl", marginBottom: 8 },
      },
      {
        type: "heading",
        slot: "col-2",
        order: 1,
        props: { text: "Smart Styles" },
        style: { fontSize: "xl", fontWeight: "semibold", marginBottom: 8 },
      },
      {
        type: "text",
        slot: "col-2",
        order: 2,
        props: { text: "Global styles that adapt to your brand automatically." },
        style: { fontSize: "sm", opacity: 70 },
      },
      {
        type: "icon",
        slot: "col-3",
        order: 0,
        props: { icon: "shield" },
        style: { fontSize: "xl", marginBottom: 8 },
      },
      {
        type: "heading",
        slot: "col-3",
        order: 1,
        props: { text: "Secure" },
        style: { fontSize: "xl", fontWeight: "semibold", marginBottom: 8 },
      },
      {
        type: "text",
        slot: "col-3",
        order: 2,
        props: { text: "Enterprise grade security for all your pages." },
        style: { fontSize: "sm", opacity: 70 },
      },
    ],
    defaultStyle: {
      backgroundColor: "#0a120f",
      paddingY: 80,
      backgroundType: "solid",
    },
    allowedBlockTypes: ["heading", "text", "button", "card", "image", "icon", "spacer", "badge", "divider", "date", "rsvp"],
  },

  cta: {
    label: "Call to Action",
    icon: "campaign",
    description: "Call-to-action section with headline and button",
    allowedLayouts: ["1col", "1col-left", "2col-3-3", "2col-4-2"],
    defaultLayoutId: "1col",
    defaultBlocks: [
      {
        type: "heading",
        slot: "main",
        order: 0,
        props: { text: "Ready to get started?" },
        style: { fontSize: "3xl", fontWeight: "bold", textAlign: "center", marginBottom: 12 },
      },
      {
        type: "text",
        slot: "main",
        order: 1,
        props: { text: "Join thousands of creators building beautiful websites." },
        style: { fontSize: "lg", textAlign: "center", marginBottom: 24, opacity: 70 },
      },
      {
        type: "button",
        slot: "main",
        order: 2,
        props: { text: "Start Free", url: "#" },
        style: { fontSize: "lg", textAlign: "center" },
      },
    ],
    defaultStyle: {
      backgroundColor: "#101b17",
      paddingY: 80,
      backgroundType: "solid",
    },
    allowedBlockTypes: ["heading", "text", "button", "card", "image", "icon", "spacer", "badge", "divider", "date", "rsvp"],
  },

  testimonials: {
    label: "Testimonials",
    icon: "format_quote",
    description: "Customer reviews and social proof",
    allowedLayouts: ["1col", "2col-3-3", "3col-2-2-2"],
    defaultLayoutId: "3col-2-2-2",
    defaultBlocks: [
      {
        type: "quote",
        slot: "col-1",
        order: 0,
        props: {
          text: "This builder made it incredibly easy to launch our landing page in just a few hours.",
          attribution: "Sarah Johnson, Marketing Director",
        },
        style: { fontSize: "base", marginBottom: 8 },
      },
      {
        type: "quote",
        slot: "col-2",
        order: 0,
        props: {
          text: "The templates are beautiful and the editor is so intuitive. Highly recommend!",
          attribution: "Mike Chen, Founder",
        },
        style: { fontSize: "base", marginBottom: 8 },
      },
      {
        type: "quote",
        slot: "col-3",
        order: 0,
        props: {
          text: "We switched from a more complex tool and never looked back. Simple and effective.",
          attribution: "Emily Davis, Designer",
        },
        style: { fontSize: "base", marginBottom: 8 },
      },
    ],
    defaultStyle: {
      backgroundColor: "#0a120f",
      paddingY: 80,
      backgroundType: "solid",
    },
    allowedBlockTypes: ["heading", "text", "quote", "card", "image", "icon", "spacer", "badge", "divider", "date"],
  },

  faq: {
    label: "FAQ",
    icon: "help",
    description: "Frequently asked questions section",
    allowedLayouts: ["1col", "1col-left"],
    defaultLayoutId: "1col",
    defaultBlocks: [
      {
        type: "heading",
        slot: "main",
        order: 0,
        props: { text: "Frequently Asked Questions" },
        style: { fontSize: "3xl", fontWeight: "bold", textAlign: "center", marginBottom: 32 },
      },
      {
        type: "heading",
        slot: "main",
        order: 1,
        props: { text: "How do I get started?" },
        style: { fontSize: "lg", fontWeight: "semibold", marginBottom: 8 },
      },
      {
        type: "text",
        slot: "main",
        order: 2,
        props: { text: "Simply sign up for a free account, choose a template, and start customizing with our drag-and-drop editor." },
        style: { fontSize: "base", marginBottom: 24, opacity: 70 },
      },
      {
        type: "heading",
        slot: "main",
        order: 3,
        props: { text: "Can I use my own domain?" },
        style: { fontSize: "lg", fontWeight: "semibold", marginBottom: 8 },
      },
      {
        type: "text",
        slot: "main",
        order: 4,
        props: { text: "Yes! You can connect your custom domain or use our free subdomain to publish your pages." },
        style: { fontSize: "base", marginBottom: 24, opacity: 70 },
      },
      {
        type: "heading",
        slot: "main",
        order: 5,
        props: { text: "Is there a free plan?" },
        style: { fontSize: "lg", fontWeight: "semibold", marginBottom: 8 },
      },
      {
        type: "text",
        slot: "main",
        order: 6,
        props: { text: "Yes, our free plan includes all core features with a free subdomain. Upgrade anytime for custom domains and more." },
        style: { fontSize: "base", opacity: 70 },
      },
    ],
    defaultStyle: {
      backgroundColor: "#101b17",
      paddingY: 80,
      backgroundType: "solid",
    },
    allowedBlockTypes: ["heading", "text", "card", "spacer", "divider", "badge", "date"],
  },

  footer: {
    label: "Footer",
    icon: "bottom_navigation",
    description: "Page footer with links and social icons",
    allowedLayouts: ["1col", "3col-2-2-2"],
    defaultLayoutId: "3col-2-2-2",
    defaultBlocks: [
      {
        type: "heading",
        slot: "col-1",
        order: 0,
        props: { text: "Product" },
        style: { fontSize: "base", fontWeight: "semibold", marginBottom: 12 },
      },
      {
        type: "list",
        slot: "col-1",
        order: 1,
        props: {
          items: [
            { text: "Features", url: "#" },
            { text: "Pricing", url: "#" },
            { text: "Templates", url: "#" },
          ],
          ordered: false,
        },
        style: { fontSize: "sm" },
      },
      {
        type: "heading",
        slot: "col-2",
        order: 0,
        props: { text: "Company" },
        style: { fontSize: "base", fontWeight: "semibold", marginBottom: 12 },
      },
      {
        type: "list",
        slot: "col-2",
        order: 1,
        props: {
          items: [
            { text: "About", url: "#" },
            { text: "Blog", url: "#" },
            { text: "Careers", url: "#" },
          ],
          ordered: false,
        },
        style: { fontSize: "sm" },
      },
      {
        type: "heading",
        slot: "col-3",
        order: 0,
        props: { text: "Support" },
        style: { fontSize: "base", fontWeight: "semibold", marginBottom: 12 },
      },
      {
        type: "list",
        slot: "col-3",
        order: 1,
        props: {
          items: [
            { text: "Help Center", url: "#" },
            { text: "Contact", url: "#" },
            { text: "Status", url: "#" },
          ],
          ordered: false,
        },
        style: { fontSize: "sm" },
      },
    ],
    defaultStyle: {
      backgroundColor: "#0a120f",
      paddingY: 60,
      backgroundType: "solid",
    },
    allowedBlockTypes: ["heading", "text", "button", "card", "icon", "list", "divider", "badge", "image", "date"],
  },

  custom: {
    label: "Blank Section",
    icon: "dashboard",
    description: "Start from an empty section and build your own structure.",
    allowedLayouts: ALL_LAYOUT_IDS,
    defaultLayoutId: "1col",
    defaultGroups: [
      {
        label: "Main Group",
        layoutId: "1col",
        blocks: [],
      },
    ],
    defaultBlocks: [],
    defaultStyle: {
      backgroundColor: "#0f1713",
      paddingY: 80,
      backgroundType: "solid",
    },
    allowedBlockTypes: ALL_BLOCK_TYPES,
  },
};
